name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Conectar a VM y desplegar
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "🚀 Hola Philippe, iniciando despliegue en la VM..."
            cd /home/admphilippe/IAHBCosteo
            git pull origin main
            source /home/admphilippe/venv-mysql/bin/activate
            pip install -r requirements.txt
            echo "✅ Despliegue completado con éxito en hidroSuiteVM"
            sudo systemctl restart iahbcosteo.service   # << este reinicia la app
