name: Test Connection to VM

on:
  push:
    branches:
      - main # o la rama que estés usando

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "✅ Hola Philippe, la conexión desde GitHub Actions funcionó!"
            hostname
            whoami
            pwd
